/**
 * Navi Protocol (lending) — Move event types (Sui mainnet), plus the Haedal
 * haSUI staking events required by the haSUI loop detector ([1C.4]).
 *
 * Generated by the U0 Sui event-discovery spike (2026-06-11). Navi's Move
 * source is unpublished; everything here was discovered from deployed
 * bytecode (`sui_getObject` disassembly -> `event::emit<T>` regex) +
 * `sui_getNormalizedMoveModulesByPackage`, then confirmed by sampling real
 * mainnet events via `suix_queryEvents` (foreign users' txs).
 *
 * The deprecated `navi-sdk` does NOT block historical decoding: events live
 * on-chain forever and are decoded from raw RPC, not through any SDK. The new
 * `@naviprotocol/lending` SDK is only needed for the assetId -> coinType pool
 * registry and the `getUserClaimedRewardHistory` cross-check.
 *
 * parsedJson rendering rules: see header of turbos-events.ts. Navi-specific:
 * `coin_type`/`pool` fields are `0x1::ascii::String` -> plain string WITHOUT
 * "0x" prefix (e.g. "bde4…::hasui::HASUI"), and asset/reserve ids are u8 -> number.
 *
 * Defining package IDs (event `type` strings carry these, NOT the currently
 * executing package version — Navi has had many upgrades):
 */

/** Defining ID for core lending::* and pool::* events (the original Navi package). */
export const NAVI_PACKAGE_LENDING =
  '0xd899cf7d2b5db716bd2cf55599fb0d5ee38a3061e7b6bb6eebf73fa5bc4c81ca';
/** Defining ID for logic::StateUpdated. */
export const NAVI_PACKAGE_LOGIC =
  '0x834a86970ae93a73faf4fff16ae40bdb72b91c47be585fff19a2af60a19ddca3';
/** Defining ID for incentive_v2::* events. */
export const NAVI_PACKAGE_INCENTIVE_V2 =
  '0xe66f07e2a8d9cf793da1e0bca98ff312b3ffba57228d97cf23a0613fddf31b65';
/** Defining ID for incentive_v3::* events. */
export const NAVI_PACKAGE_INCENTIVE_V3 =
  '0x81c408448d0d57b3e371ea94de1d40bf852784d3e225de1e74acab3e8395c18f';
/** Defining ID for flash_loan::* events. */
export const NAVI_PACKAGE_FLASH_LOAN =
  '0x06007a2d0ddd3ef4844c6d19c83f71475d6d3ac2d139188d6b62c052e6965edd';
/**
 * Latest package version observed at discovery time (use for MoveModule
 * queryEvents filters / getNormalizedMoveModulesByPackage). The canonical way
 * to obtain the current version at runtime is
 * `getConfig({ env: 'prod' }).package` from `@naviprotocol/lending`
 * (https://open-api.naviprotocol.io/api/navi/config).
 */
export const NAVI_PACKAGE_OBSERVED_LATEST =
  '0xee0041239b89564ce870a7dec5ddc5d114367ab94a1137e90aa0633cb76518e0';
/** Navi protocol storage object (stable across upgrades; handy for tx filtering). */
export const NAVI_STORAGE_OBJECT =
  '0xbb4e2f4b6205c2e2a2db47aeb4f830796ec7c005f88537ee775986639bc442fe';

// ---------------------------------------------------------------------------
// lending module — core user actions
// `reserve`/`asset` is the Navi asset index (u8); map to coin type via the
// pool registry (`getPools()` from @naviprotocol/lending). `sender` is the
// wallet. Amounts are raw (decimal-scaled per asset).
// ---------------------------------------------------------------------------

/** Supply collateral. Tax: lend_supply/deposit. */
export interface NaviDepositEvent {
  reserve: number;
  sender: string;
  amount: string;
}

/** Withdraw collateral. Tax: lend_supply/withdraw. */
export interface NaviWithdrawEvent {
  reserve: number;
  sender: string;
  to: string;
  amount: string;
}

/** Borrow against collateral. Tax: lend_borrow/borrow (not income). */
export interface NaviBorrowEvent {
  reserve: number;
  sender: string;
  amount: string;
}

/** Repay debt. Tax: lend_borrow/repay. */
export interface NaviRepayEvent {
  reserve: number;
  sender: string;
  amount: string;
}

/**
 * Liquidation. `user` is the liquidated wallet (tax: liquidation/* when it is
 * an owned wallet). Defining package UNCONFIRMED (no live sample found at
 * lending/logic/incentive defining IDs) — match by `::lending::LiquidationEvent`
 * suffix until a real fixture pins it down.
 */
export interface NaviLiquidationEvent {
  sender: string;
  user: string;
  collateral_asset: number;
  collateral_price: string;
  collateral_amount: string;
  treasury: string;
  debt_asset: number;
  debt_price: string;
  debt_amount: string;
}

/** Deposit executed for another wallet. Defining package unconfirmed — suffix-match. */
export interface NaviDepositOnBehalfOfEvent {
  reserve: number;
  sender: string;
  user: string;
  amount: string;
}

/** Repay executed for another wallet. Defining package unconfirmed — suffix-match. */
export interface NaviRepayOnBehalfOfEvent {
  reserve: number;
  sender: string;
  user: string;
  amount: string;
}

// ---------------------------------------------------------------------------
// pool module — fund-flow companions to lending::* (same tx)
// ---------------------------------------------------------------------------

/** Coins entering a Navi pool. `pool` = coin type string (no 0x prefix). */
export interface NaviPoolDeposit {
  sender: string;
  amount: string;
  pool: string;
}

/** Coins leaving a Navi pool. */
export interface NaviPoolWithdraw {
  sender: string;
  recipient: string;
  amount: string;
  pool: string;
}

// ---------------------------------------------------------------------------
// logic module — per-action interest-index bookkeeping (emitted with every action)
// ---------------------------------------------------------------------------

/** Balance/index snapshot after an action. Source for lend_interest accrual reconstruction. */
export interface NaviStateUpdated {
  user: string;
  asset: number;
  user_supply_balance: string;
  user_borrow_balance: string;
  new_supply_index: string;
  new_borrow_index: string;
}

// ---------------------------------------------------------------------------
// incentive_v2 / incentive_v3 modules — reward claims
// Cross-check coverage against getUserClaimedRewardHistory() (Navi HTTP API).
// ---------------------------------------------------------------------------

/** Legacy reward claim (incentive v2). `pool` is the funds-pool object. Tax: lend_reward/claim. */
export interface NaviRewardsClaimedV2 {
  sender: string;
  pool: string;
  amount: string;
}

/** Current reward claim (incentive v3). Tax: lend_reward/claim. */
export interface NaviRewardClaimedV3 {
  user: string;
  total_claimed: string;
  /** Reward coin type, plain string without 0x prefix. */
  coin_type: string;
  rule_ids: string[];
  rule_indices: string[];
}

// ---------------------------------------------------------------------------
// flash_loan module
// ---------------------------------------------------------------------------

/** Flash loan taken (repaid in same tx — flag `flash_loan`, not a taxable borrow). */
export interface NaviFlashLoan {
  sender: string;
  asset: string;
  amount: string;
}

/** Flash loan repaid. */
export interface NaviFlashRepay {
  sender: string;
  asset: string;
  amount: string;
  fee_to_supplier: string;
  fee_to_treasury: string;
}

export const NAVI_EVENT_TYPES = {
  deposit: `${NAVI_PACKAGE_LENDING}::lending::DepositEvent`,
  withdraw: `${NAVI_PACKAGE_LENDING}::lending::WithdrawEvent`,
  borrow: `${NAVI_PACKAGE_LENDING}::lending::BorrowEvent`,
  repay: `${NAVI_PACKAGE_LENDING}::lending::RepayEvent`,
  poolDeposit: `${NAVI_PACKAGE_LENDING}::pool::PoolDeposit`,
  poolWithdraw: `${NAVI_PACKAGE_LENDING}::pool::PoolWithdraw`,
  stateUpdated: `${NAVI_PACKAGE_LOGIC}::logic::StateUpdated`,
  rewardsClaimedV2: `${NAVI_PACKAGE_INCENTIVE_V2}::incentive_v2::RewardsClaimed`,
  rewardClaimedV3: `${NAVI_PACKAGE_INCENTIVE_V3}::incentive_v3::RewardClaimed`,
  flashLoan: `${NAVI_PACKAGE_FLASH_LOAN}::flash_loan::FlashLoan`,
  flashRepay: `${NAVI_PACKAGE_FLASH_LOAN}::flash_loan::FlashRepay`,
} as const;

export type NaviEventType = (typeof NAVI_EVENT_TYPES)[keyof typeof NAVI_EVENT_TYPES];

/**
 * Events whose defining package is unconfirmed — match `SuiEvent.type` by
 * these suffixes (cheap and unambiguous: module+name collisions across
 * unrelated packages are filtered by the tx touching NAVI_STORAGE_OBJECT).
 */
export const NAVI_EVENT_TYPE_SUFFIXES = {
  liquidation: '::lending::LiquidationEvent',
  depositOnBehalfOf: '::lending::DepositOnBehalfOfEvent',
  repayOnBehalfOf: '::lending::RepayOnBehalfOfEvent',
} as const;

export interface NaviEventPayloadMap {
  deposit: NaviDepositEvent;
  withdraw: NaviWithdrawEvent;
  borrow: NaviBorrowEvent;
  repay: NaviRepayEvent;
  liquidation: NaviLiquidationEvent;
  depositOnBehalfOf: NaviDepositOnBehalfOfEvent;
  repayOnBehalfOf: NaviRepayOnBehalfOfEvent;
  poolDeposit: NaviPoolDeposit;
  poolWithdraw: NaviPoolWithdraw;
  stateUpdated: NaviStateUpdated;
  rewardsClaimedV2: NaviRewardsClaimedV2;
  rewardClaimedV3: NaviRewardClaimedV3;
  flashLoan: NaviFlashLoan;
  flashRepay: NaviFlashRepay;
}

// ===========================================================================
// Haedal haSUI staking — needed by the haSUI loop detector ([1C.4]).
//
// Loop signature within ONE tx digest (PTB), repeated 1..n times:
//   1. NaviDepositEvent   (reserve == haSUI assetId)  + NaviPoolDeposit(pool == hasui::HASUI)
//   2. NaviBorrowEvent    (reserve == SUI assetId)    + NaviPoolWithdraw(pool == sui::SUI)
//   3. HaedalUserStaked   (sui_amount in, st_amount = haSUI minted)
//   4. goto 1 (re-deposit of freshly minted haSUI)
// Unwind direction uses HaedalUserInstantUnstaked / UserNormalUnstaked +
// NaviRepayEvent. Tag all constituent TaxEvents with flag `looping_pattern`.
// ===========================================================================

/** Defining ID for Haedal staking::* events (= the haSUI coin package). */
export const HAEDAL_PACKAGE_DEFINING =
  '0xbde4ba4c2e274a60ce15c1cfff9e5c42e41654ac8b6d906a57efa4bd3c29f47d';
/** Current Haedal staking package (for normalized-module lookups / call targets). */
export const HAEDAL_PACKAGE_CURRENT =
  '0x19e6ea7f5ced4f090e20da794cc80349a03e638940ddb95155a4e301f5f4967c';
export const HASUI_COIN_TYPE = `${HAEDAL_PACKAGE_DEFINING}::hasui::HASUI`;

/** SUI staked -> haSUI minted. Tax: swap/trade (SUI -> haSUI) under §23, or stake/delegate — policy decision in docs/tax-policy.md. */
export interface HaedalUserStaked {
  owner: string;
  sui_amount: string;
  st_amount: string;
  validator: string;
}

/** haSUI burned -> SUI returned instantly (fee applies). */
export interface HaedalUserInstantUnstaked {
  owner: string;
  sui_amount: string;
  st_amount: string;
}

/** haSUI burned -> delayed unstake ticket (SUI claimable next epoch(s)). */
export interface HaedalUserNormalUnstaked {
  owner: string;
  epoch: string;
  epoch_timestamp_ms: string;
  unstake_timestamp_ms: string;
  sui_amount: string;
  st_amount: string;
}

/** SUI claimed from a matured unstake ticket. */
export interface HaedalUserClaimed {
  id: string;
  owner: string;
  sui_amount: string;
}

export const HAEDAL_EVENT_TYPES = {
  userStaked: `${HAEDAL_PACKAGE_DEFINING}::staking::UserStaked`,
  userInstantUnstaked: `${HAEDAL_PACKAGE_DEFINING}::staking::UserInstantUnstaked`,
  userNormalUnstaked: `${HAEDAL_PACKAGE_DEFINING}::staking::UserNormalUnstaked`,
  userClaimed: `${HAEDAL_PACKAGE_DEFINING}::staking::UserClaimed`,
} as const;

export type HaedalEventType = (typeof HAEDAL_EVENT_TYPES)[keyof typeof HAEDAL_EVENT_TYPES];

export interface HaedalEventPayloadMap {
  userStaked: HaedalUserStaked;
  userInstantUnstaked: HaedalUserInstantUnstaked;
  userNormalUnstaked: HaedalUserNormalUnstaked;
  userClaimed: HaedalUserClaimed;
}
