/**
 * Turbos Finance CLMM — Move event types (Sui mainnet).
 *
 * Generated by the U0 Sui event-discovery spike (2026-06-11), mirroring the
 * `sui-events-indexer` bootstrap approach: `sui_getObject` bytecode disassembly
 * -> `event::emit<T>` extraction -> `sui_getNormalizedMoveModulesByPackage`
 * struct lookup -> empirical confirmation via `suix_queryEvents` sampling of
 * real mainnet events (foreign users' txs — own wallet history not yet ingested).
 *
 * Interfaces model the `parsedJson` payload of `SuiEvent` as returned by
 * JSON-RPC (`showEvents: true`), NOT the raw BCS layout:
 *   - u64 / u128 / u256  -> decimal string
 *   - u8 / u16 / u32     -> number
 *   - address, 0x2::object::ID -> "0x…" string
 *   - 0x1::string::String / 0x1::ascii::String -> string
 *   - 0x1::type_name::TypeName -> { name: string }  (name has NO "0x" prefix)
 *   - i32::I32 (Turbos signed int) -> { bits: number } (two's-complement u32)
 *
 * See docs/sui-event-discovery.md for the full discovery log.
 */

/**
 * Original (v1) package — the defining ID for all v1 event types. Emitted
 * event `type` strings for v1 events carry THIS address even when the tx
 * executed a later package version.
 * Confirmed by sampling: e.g. `…::pool::SwapEvent` on tx 67eaPfSAHQxqMX9uc86KavSNp65774yxJsED2Y6nWWup.
 */
export const TURBOS_PACKAGE_V1 = '0x91bfbc386a41afcfd9b2533058d7e915a1d3829089cc268ff4333d54d6339ca1';

/**
 * Current published package (v0.1.8 era, 33 modules) — the defining ID for
 * events introduced after v1 (`CollectEventV2`, `CollectRewardEventV2`,
 * `MintNftEvent`, `BurnNftEvent`, partner module, …).
 * Also the package to use for `MoveModule` queryEvents filters — filtering on
 * the v1 package misses events emitted via the upgraded package.
 */
export const TURBOS_PACKAGE_CURRENT =
  '0xa5a0c25c79e428eba04fb98b3fb2a34db45ab26d4c8faf0d7e39d66a63891e64';

/**
 * Turbos signed 32-bit integer as rendered in parsedJson.
 * Decode: `bits >= 2 ** 31 ? bits - 2 ** 32 : bits`.
 */
export interface TurbosI32 {
  bits: number;
}

// ---------------------------------------------------------------------------
// pool module (defining package: v1 unless noted)
// ---------------------------------------------------------------------------

/** Liquidity added to a position (also emitted on position open). Tax: lp_deposit. */
export interface TurbosPoolMintEvent {
  pool: string;
  owner: string;
  tick_lower_index: TurbosI32;
  tick_upper_index: TurbosI32;
  amount_a: string;
  amount_b: string;
  liquidity_delta: string;
}

/** Liquidity removed from a position. Tax: lp_withdraw. */
export interface TurbosPoolBurnEvent {
  pool: string;
  owner: string;
  tick_lower_index: TurbosI32;
  tick_upper_index: TurbosI32;
  amount_a: string;
  amount_b: string;
  liquidity_delta: string;
}

/** Swap in a single pool. Multi-hop routes emit one SwapEvent per pool. Tax: swap. */
export interface TurbosSwapEvent {
  pool: string;
  recipient: string;
  amount_a: string;
  amount_b: string;
  liquidity: string;
  tick_current_index: TurbosI32;
  tick_pre_index: TurbosI32;
  sqrt_price: string;
  protocol_fee: string;
  fee_amount: string;
  a_to_b: boolean;
  is_exact_in: boolean;
}

/** Fee collection (v1 — historical txs only; superseded by CollectEventV2). Tax: lp_fee. */
export interface TurbosCollectEvent {
  pool: string;
  recipient: string;
  tick_lower_index: TurbosI32;
  tick_upper_index: TurbosI32;
  amount_a: string;
  amount_b: string;
}

/** Fee collection (current, adds `owner`). Defining package: CURRENT. Tax: lp_fee. */
export interface TurbosCollectEventV2 {
  pool: string;
  owner: string;
  recipient: string;
  tick_lower_index: TurbosI32;
  tick_upper_index: TurbosI32;
  amount_a: string;
  amount_b: string;
}

/** Reward collection (v1 — historical txs only). Tax: lp_reward. */
export interface TurbosCollectRewardEvent {
  pool: string;
  recipient: string;
  tick_lower_index: TurbosI32;
  tick_upper_index: TurbosI32;
  amount: string;
  vault: string;
  reward_index: string;
}

/** Reward collection (current, adds owner + reward coin type). Defining package: CURRENT. Tax: lp_reward. */
export interface TurbosCollectRewardEventV2 {
  pool: string;
  recipient: string;
  owner: string;
  tick_lower_index: TurbosI32;
  tick_upper_index: TurbosI32;
  amount: string;
  vault: string;
  /** Reward coin type, e.g. { name: "0000…0002::sui::SUI" } (no 0x prefix). */
  reward_type: { name: string };
  reward_index: string;
}

/** Protocol-fee sweep by Turbos team. Not user-tax-relevant. */
export interface TurbosCollectProtocolFeeEvent {
  pool: string;
  recipient: string;
  amount_a: string;
  amount_b: string;
}

/** Admin: position storage-key migration. Defining package: CURRENT (unconfirmed — never sampled). */
export interface TurbosMigratePositionEvent {
  pool: string;
  old_key: string;
  new_key: string;
}

// ---------------------------------------------------------------------------
// position_manager module
// ---------------------------------------------------------------------------

/** Companion to pool::MintEvent in the same tx; lacks owner/ticks. Tax: lp_deposit. */
export interface TurbosIncreaseLiquidityEvent {
  pool: string;
  amount_a: string;
  amount_b: string;
  liquidity: string;
}

/** Companion to pool::BurnEvent in the same tx. Tax: lp_withdraw. */
export interface TurbosDecreaseLiquidityEvent {
  pool: string;
  amount_a: string;
  amount_b: string;
  liquidity: string;
}

/** Position-manager-level fee collect (v1; emitted alongside pool::CollectEvent). */
export interface TurbosPmCollectEvent {
  pool: string;
  amount_a: string;
  amount_b: string;
  recipient: string;
}

/** Position-manager-level reward collect (v1; emitted alongside pool::CollectRewardEvent). */
export interface TurbosPmCollectRewardEvent {
  pool: string;
  amount: string;
  vault: string;
  reward_index: string;
  recipient: string;
}

/**
 * Position NFT minted — links nft_address to the in-pool position_id.
 * THE positionId source for CLMM lifecycle tracking. Defining package: CURRENT.
 */
export interface TurbosMintNftEvent {
  nft_address: string;
  position_id: string;
  pool_id: string;
}

/** Position NFT burned (position closed). Defining package: CURRENT. */
export interface TurbosBurnNftEvent {
  nft_address: string;
  position_id: string;
  pool_id: string;
}

/** Position burned via burn_position_nft_directly. Defining package: CURRENT (unconfirmed — never sampled). */
export interface TurbosBurnPositionEvent {
  nft_address: string;
  position_id: string;
  pool_id: string;
  burn_nft_address: string;
}

// ---------------------------------------------------------------------------
// position_nft module (v1 only)
// ---------------------------------------------------------------------------

/** Legacy NFT mint marker (v1 txs). object_id == NFT address. */
export interface TurbosMintNFTEventV1 {
  object_id: string;
  creator: string;
  name: string;
}

// ---------------------------------------------------------------------------
// pool_factory module
// ---------------------------------------------------------------------------

/** Pool created. Useful for pool -> (coinA, coinB, fee) registry bootstrap. */
export interface TurbosPoolCreatedEvent {
  account: string;
  pool: string;
  fee: number;
  tick_spacing: number;
  fee_protocol: number;
  sqrt_price: string;
}

/**
 * Fully-qualified event type strings as they appear in `SuiEvent.type`.
 * Keyed by defining package (NOT the package version the tx executed).
 *
 * Admin/config events intentionally excluded from decoding scope (full list in
 * docs/sui-event-discovery.md): pool::{AddRewardEvent, InitRewardEvent,
 * RemoveRewardEvent, TogglePoolStatusEvent, UpdatePoolFeeProtocolEvent,
 * UpdateRewardEmissionsEvent, UpdateRewardManagerEvent, UpgradeEvent},
 * pool_factory::{FeeAmountEnabledEvent, SetFeeProtocolEvent, AddRoleEvent,
 * RemoveMemberEvent, RemoveRoleEvent, SetRolesEvent}, partner::*,
 * pool_fetcher::FetchTicksResultEvent.
 */
export const TURBOS_EVENT_TYPES = {
  poolMint: `${TURBOS_PACKAGE_V1}::pool::MintEvent`,
  poolBurn: `${TURBOS_PACKAGE_V1}::pool::BurnEvent`,
  swap: `${TURBOS_PACKAGE_V1}::pool::SwapEvent`,
  collect: `${TURBOS_PACKAGE_V1}::pool::CollectEvent`,
  collectV2: `${TURBOS_PACKAGE_CURRENT}::pool::CollectEventV2`,
  collectReward: `${TURBOS_PACKAGE_V1}::pool::CollectRewardEvent`,
  collectRewardV2: `${TURBOS_PACKAGE_CURRENT}::pool::CollectRewardEventV2`,
  collectProtocolFee: `${TURBOS_PACKAGE_V1}::pool::CollectProtocolFeeEvent`,
  increaseLiquidity: `${TURBOS_PACKAGE_V1}::position_manager::IncreaseLiquidityEvent`,
  decreaseLiquidity: `${TURBOS_PACKAGE_V1}::position_manager::DecreaseLiquidityEvent`,
  pmCollect: `${TURBOS_PACKAGE_V1}::position_manager::CollectEvent`,
  pmCollectReward: `${TURBOS_PACKAGE_V1}::position_manager::CollectRewardEvent`,
  mintNft: `${TURBOS_PACKAGE_CURRENT}::position_manager::MintNftEvent`,
  burnNft: `${TURBOS_PACKAGE_CURRENT}::position_manager::BurnNftEvent`,
  burnPosition: `${TURBOS_PACKAGE_CURRENT}::position_manager::BurnPositionEvent`,
  mintNftV1: `${TURBOS_PACKAGE_V1}::position_nft::MintNFTEvent`,
  poolCreated: `${TURBOS_PACKAGE_V1}::pool_factory::PoolCreatedEvent`,
} as const;

export type TurbosEventType = (typeof TURBOS_EVENT_TYPES)[keyof typeof TURBOS_EVENT_TYPES];

/** parsedJson payload type per event-type key. */
export interface TurbosEventPayloadMap {
  poolMint: TurbosPoolMintEvent;
  poolBurn: TurbosPoolBurnEvent;
  swap: TurbosSwapEvent;
  collect: TurbosCollectEvent;
  collectV2: TurbosCollectEventV2;
  collectReward: TurbosCollectRewardEvent;
  collectRewardV2: TurbosCollectRewardEventV2;
  collectProtocolFee: TurbosCollectProtocolFeeEvent;
  increaseLiquidity: TurbosIncreaseLiquidityEvent;
  decreaseLiquidity: TurbosDecreaseLiquidityEvent;
  pmCollect: TurbosPmCollectEvent;
  pmCollectReward: TurbosPmCollectRewardEvent;
  mintNft: TurbosMintNftEvent;
  burnNft: TurbosBurnNftEvent;
  burnPosition: TurbosBurnPositionEvent;
  mintNftV1: TurbosMintNFTEventV1;
  poolCreated: TurbosPoolCreatedEvent;
}
